"""user_id added to appointment

Revision ID: 287eb782674c
Revises: c3e7f9a12b04
Create Date: 2026-05-11 12:01:11.086155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287eb782674c'
down_revision: Union[str, Sequence[str], None] = 'c3e7f9a12b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'user_id')
    # ### end Alembic commands ###
