"""adición de catálogo de tipo de servicio

Revision ID: ae8880842935
Revises: 8f3a2b1c0d9e
Create Date: 2026-05-05 17:13:17.985893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae8880842935'
down_revision: Union[str, Sequence[str], None] = '8f3a2b1c0d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('service_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'services', 'services_type', ['service_type_id'], ['id'])
    op.drop_column('services_type', 'enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services_type', sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'service_type_id')
    # ### end Alembic commands ###
