"""Cambios en modelo de citas y cliente

Revision ID: d2c4a26638c9
Revises: 
Create Date: 2026-05-04 19:03:39.780754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Mismos strings que PromotionType.value (como AppointmentStatus + Field simple en SQLModel).
PROMOTION_VALUES = ("discount", "service_free", "no_promotion")


# revision identifiers, used by Alembic.
revision: str = 'd2c4a26638c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_service_links')

    promotion_enum = postgresql.ENUM(
        *PROMOTION_VALUES,
        name="promotiontype",
    )
    promotion_enum.create(op.get_bind(), checkfirst=True)

    promotion_column_type = postgresql.ENUM(
        *PROMOTION_VALUES,
        name="promotiontype",
        create_type=False,
    )
    op.add_column(
        "appointments",
        sa.Column(
            "promotion",
            promotion_column_type,
            nullable=False,
            server_default=sa.text("'no_promotion'::promotiontype"),
        ),
    )
    op.alter_column("appointments", "promotion", server_default=None)

    op.add_column("appointments", sa.Column("subtotal", sa.Float(), nullable=False))
    op.add_column("appointments", sa.Column("total", sa.Float(), nullable=False))
    op.add_column(
        "clients",
        sa.Column("loyalty_completed", sa.Integer(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'loyalty_completed')
    op.drop_column('appointments', 'total')
    op.drop_column('appointments', 'subtotal')
    op.drop_column('appointments', 'promotion')

    promotion_enum = postgresql.ENUM(
        *PROMOTION_VALUES,
        name="promotiontype",
        create_type=False,
    )
    promotion_enum.drop(op.get_bind(), checkfirst=True)
    op.create_table('appointment_service_links',
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('appointment_service_links_appointment_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('appointment_service_links_service_id_fkey')),
    sa.PrimaryKeyConstraint('appointment_id', 'service_id', name=op.f('appointment_service_links_pkey'))
    )
    # ### end Alembic commands ###
