"""adición de catalogo de promociones

Revision ID: f61f03471ba9
Revises: ae8880842935
Create Date: 2026-05-05 18:16:52.862321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f61f03471ba9'
down_revision: Union[str, Sequence[str], None] = 'ae8880842935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('modified_by', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('appointments', sa.Column('promotion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'promotions', ['promotion_id'], ['id'])
    op.drop_column('appointments', 'promotion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('promotion', postgresql.ENUM('DISCOUNT', 'SERVICE_FREE', 'NO_PROMOTION', name='promotiontype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'promotion_id')
    op.drop_table('promotions')
    # ### end Alembic commands ###
